#define CAPS_LOCK_INDEX 61
#define SCROLL_LOCK_INDEX 14

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_DEFAULT_HUE 106
#define RGB_MATRIX_DEFAULT_SAT 63
#define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
#define HOLD_ON_OTHER_KEY_PRESS
